{
 "title": "ML Model Metrics",
 "tags": [ "ML Metrics" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "New Panel",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 15, "x": 0, "y": 0 },
   "targets": [
    { "expr": "model_mae", "legendFormat": "__auto" },
    { "expr": "model_mse", "legendFormat": "__auto" },
    { "expr": "model_r2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Model R²",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_r2", "legendFormat": "R²" }
   ]
  },
  {
   "title": "Model MSE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_mse", "legendFormat": "MSE" }
   ]
  },
  {
   "title": "Model MAE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_mae", "legendFormat": "MAE" }
   ]
  }
 ]
}